#!/usr/bin/env bash
# Generates the FreeRADIUS flat-file users database and companion CSV credential files
#
# Purpose:
#   Produces three outputs from a single seeded source of truth:
#     1. test/docker/freeradius/users  — FreeRADIUS flat-file user DB (5000 entries)
#     2. test/fixtures/credentials/smoke-100.csv   — first 100 users for smoke tests
#     3. test/fixtures/credentials/test-1k.csv     — first 1000 users for 1k scenario
#   Username format: sub00000001 ... sub00005000
#   Password format: pw00000001  ... pw00005000
#   All users get Cleartext-Password so both PAP and CHAP auth work.
#
# Related: test/docker/freeradius/Dockerfile, test/fixtures/scenarios/smoke-100.toml,
#          test/fixtures/scenarios/test-1k.toml,
#          .orchestration/contracts/config-schema.md (credentials CSV format)
# Briefing: .orchestration/briefings/1e-docker-rig.md
# Contract: CSV header: username,password,auth_method,sub_type,nas_port_id,mac_address

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

USERS_FILE="${REPO_ROOT}/test/docker/freeradius/users"
CREDENTIALS_DIR="${REPO_ROOT}/test/fixtures/credentials"
SMOKE_CSV="${CREDENTIALS_DIR}/smoke-100.csv"
TEST1K_CSV="${CREDENTIALS_DIR}/test-1k.csv"

TOTAL_USERS=5000
SMOKE_COUNT=100
TEST1K_COUNT=1000

echo "Generating ${TOTAL_USERS} seeded test users..."

mkdir -p "${CREDENTIALS_DIR}"

# ── FreeRADIUS users file ────────────────────────────────────────────────────
cat > "${USERS_FILE}" << 'HEADER'
# FreeRADIUS flat-file user database — AUTO-GENERATED by test/docker/seed/generate-users.sh
# DO NOT EDIT BY HAND. Re-run the seed script to regenerate.
#
# Purpose: Defines 5000 test users for the radstorm local Docker test rig.
# Related: test/docker/freeradius/sites-enabled/default (uses "files" module)
# Briefing: .orchestration/briefings/1e-docker-rig.md
# Contract: sub00000001/pw00000001 ... sub00005000/pw00005000, all Cleartext-Password
HEADER

for i in $(seq 1 ${TOTAL_USERS}); do
    username=$(printf "sub%08d" ${i})
    password=$(printf "pw%08d" ${i})
    printf '%s\tCleartext-Password := "%s"\n' "${username}" "${password}" >> "${USERS_FILE}"
done

echo "  Written: ${USERS_FILE} (${TOTAL_USERS} entries)"

# ── CSV credential files ─────────────────────────────────────────────────────
CSV_HEADER="username,password,auth_method,sub_type,nas_port_id,mac_address"

generate_csv() {
    local outfile="$1"
    local count="$2"

    {
        echo "# AUTO-GENERATED by test/docker/seed/generate-users.sh — DO NOT EDIT"
        echo "${CSV_HEADER}"
        for i in $(seq 1 ${count}); do
            username=$(printf "sub%08d" ${i})
            password=$(printf "pw%08d" ${i})
            # Alternate pap/chap to exercise both code paths
            if (( i % 2 == 0 )); then
                auth_method="chap"
            else
                auth_method="pap"
            fi
            # Simple NAS-Port-Id pattern: slot 1/port 1/vlan i
            nas_port_id=$(printf "1/1/%d" ${i})
            # Pseudo-MAC: aa:bb:cc:00:XX:XX where XX encodes the subscriber index
            mac_hi=$(printf "%02x" $(( (i >> 8) & 0xff )))
            mac_lo=$(printf "%02x" $(( i & 0xff )))
            mac="aa:bb:cc:00:${mac_hi}:${mac_lo}"
            printf '%s,%s,%s,pppoe,%s,%s\n' \
                "${username}" "${password}" "${auth_method}" "${nas_port_id}" "${mac}"
        done
    } > "${outfile}"

    echo "  Written: ${outfile} (${count} entries)"
}

generate_csv "${SMOKE_CSV}" "${SMOKE_COUNT}"
generate_csv "${TEST1K_CSV}" "${TEST1K_COUNT}"

echo "Done. Seed complete."
